---
- hosts: all
  connection: local
  vars_files:
    - default.config.yml
  vars_prompt:
    - name: GITHUB_ACCESS_TOKEN
      prompt: "What is your github access token (PAT)?"

  roles:
    - role: setup_homebrew
    - role: setup_dotfiles
      when: configure_dotfiles
    - role: setup_terminal
      when: configure_terminal
    - role: setup_macos
      when: configure_osx

  post_tasks:
    - name: Check if Claude Code CLI is installed
      ansible.builtin.shell: command -v claude
      register: claude_installed
      failed_when: false
      changed_when: false

    - name: Install Claude Code plugins
      ansible.builtin.shell: |
        claude --plugin install claude-mem@thedotmack
        claude --plugin install everything-claude-code@everything-claude-code
      args:
        executable: /bin/zsh
      when: configure_terminal and claude_installed.rc == 0
      ignore_errors: yes
      tags:
        - claude-plugins
